config/routes.rb
LooklaDev::Application.routes.draw do

  resources :gammes

  get "static/index"
  resources :activites do
    member do
      get :export
      post :validate_personne_by_name
    end
    collection do
      get :import
      put :import_product_as_activite , as: :ipap
      put :import_cat_product_as_activite , as: :icpap
      get :validate_personne_by_ean
      post :validate_personne_by_ean
      post :recap
      get :recap
    end
  end

  get "commande_products/check_nombre"
  post "commande_products/check_nombre"
  post "commande_products/validate/:id" => 'commande_products#validate', as: 'commande_products_validate'
  get "admin/index"
  get "admin/check_in"
  get "admin/graph"
  get "home/index"
  get "home/team"
  get "home/pack"
  get "home/pistes"
  get "home/event"
  get "home/histoire"
  get "home/soirees"
  resources :commandes do
	
    member do
      post :add_product
      post :remove_product
      post :maj_cat_product
      get :catalogue
      post :maj_product_personne_preference
    end
    collection do
      post :check_in
      get :export
	  get :export_last_payment
      get :add_caution
      post :validate_caution
      post :validate_caution_batch
      get :index_ean
      post :get_infos
      get :get_infos
    end
    resources :paiements
    get :show_recap
  end
  get 'remboursements' => 'commandes#index_remboursement', as: :remboursements

  get "chart/etatcommande" => "chart#etatcommande"
  get "chart/paiement" => "chart#paiement"
  get "chart/etapepaiement" => "chart#etapepaiement"
  get "chart/tbkcommandes" => "chart#tbkcommandes"
  get "chart/statsinsctiptions" => "chart#statsinsctiptions"
  get "chart/choix_resids" => "chart#choix_resids"
  get "chart/statsbus/:categorie_id/:event_id" => "chart#statsbus", as: :statsbus

  resources :events do
    resources :products
  end
  resources :paiements do
    put :force_validation, :on => :collection
    collection do
      get 'to_moderate'
      get 'export_attente'   
    end
    member do
      get 'remove_from_pending_list'
    end
  end

  post 'paiement-check-lydia-ok' => 'paiements#check_lydia_ok'
  post 'paiement-check-lydia-nok' => 'paiements#check_lydia_nok'
  post 'paiement-check-lydia-expire' => 'paiements#check_lydia_expire'

  get 'paiements-check' => 'paiements#check', as: :check_paiement
  post 'paiements-import-csv' => 'paiements#csv_import', as: :csv_import

  resources :personnes do
    member do
      get 'personne_infos'
      get 'typeresids'
      get 'choix_chambre'
      post 'choix_lit'
      get 'refresh_list_lits'
      post 'personne_infos' => "personnes#update_personne_infos"
      post 'typeresids' => "personnes#update_personne_infos"
      get 'add_commande'
    end
    collection do
      get 'export'
      get 'to_moderate'
      get 'add_assurance'
    end
    resources :commandes do
      resources :events do
        resources :products
      end
    end
  get :autocomplete_personne_nom, :on => :collection
  post :validate_assurance, :on => :collection
  post :validate_assurance_batch, :on => :collection
  end
  resources :products
  get 'productnmbr' => 'comandes#productnmbr'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    member do
      get 'cgu'
      post 'cgu'=>"users#cgu_accept"
      get 'user_infos'
      post 'user_infos'=>"users#update_user_infos"
      get 'dashboard'
      get 'parrainer'
      post 'parrainer'=>"users#create_parrainer"
      get 'new_personne'
    end
    collection do
      get 'to_moderate'
      get 'register/:token', to: "users#register", as: :register
      post 'register/:token'=>"users#create_register"
    end
  end

  resources :chambres, only: [:index, :create] do
    get :autocomplete_personne_nom, :on => :collection
    collection do
      get 'import'
      post 'import' => 'chambres#import_validate'
      get 'assign'
      get 'recap_boulangerie'
    end
    member do
      get 'get_personnes_for'
      get 'add_personne'
      post 'add_personne'
      get 'remove_personne'
      post 'remove_personne'
    end
  end

  resources :preregistrations
  resources :typeresids
  resources :lits do
    collection do
      get 'import'
      post 'import' => 'chambres#import_validate'
    end
  end

  root :to => "home#index"

end

app/views/admin/check_in.html.haml
%div.top-info.pa1
  %h1 Check-In
%div.fiche.pa1.brdr-b
  .pers_selection
    .assign_pers_form
      
      =form_tag check_in_commandes_path, :class =>"no-enter" do
        =text_field_tag 'ean', '' , :size => 13 ,:autofocus => true, :class => 'auto_submit'
        =#submit_tag "Check-In !"
      #error_box
        

  .commande
    %h2 Infos
    .info
      %strong Nom :
      %span#nom_complet Nom Complet


  .chambre
    %h2 Chambre
    .infos
      %h3 Identifiant :
      #id_chambre
    .personnes
      %h3 Autre membres de la chambre
      %table
        %thead
          %tr
            %th Nom
            %th Assurance
            %th Caution
            %th Paiement
        %tbody#chambree

app/views/admin/graph.html.haml
.shadow-1
	%div.top-info.pa1
		%h1 Graph Admin





	%div.fiche.pa1.brdr-b
		.grid
			.grid2
				-@event.each do |e|
					%div
						%h2=e.name
						%p
							nombre de commandes
							=e.commandes.count

	%div.fiche.pa1.brdr-b
		%h2 Inscriptions
		%span= column_chart chart_statsinsctiptions_path
.shadow-1
	%div.top-info.pa1
		%h2 Commandes
	%div.fiche.pa1.brdr-b
		%div.row
			%div.col.w50
				%p
					nombre de commande: 
					=@nbrCommande
				%p
					nombre de commandes validées: 
					=@nbrCommandeValidee
			%div.col.w50
				%span= pie_chart [["Commandes validées",@nbrCommandeValidee],["Commandes non validées",@nbrCommandesNonValidee ]]

.shadow-1
	%div.top-info.pa1
		%h2 Commandes
	%div.fiche.pa1.brdr-b
		%h3 Commandes incomplètes
		%span= bar_chart chart_etatcommande_path
		%h3 Commandes gérées par chaque tbk
		%span= pie_chart chart_tbkcommandes_path


.shadow-1
	%div.top-info.pa1
		%h2 Paiements
	%div.fiche.pa1.brdr-b
		%span= pie_chart chart_paiement_path
		%h3 Étapes paiement
		%span= bar_chart chart_etapepaiement_path

.shadow-1
	%div.top-info.pa1
		%h2 Résidence
	%div.fiche.pa1.brdr-b
		Répartitions des chambres pour les personnes qui ont effectuées au moins un paiement. Les autres ne sont pas comptabilisées
		%span= bar_chart chart_choix_resids_path
	
.shadow-1
	%div.top-info.pa1
		%h2 Produits
	%div.fiche.pa1.brdr-b
		-@event.each do |e|
			%div.row
				 
				%div.col.w50
					%h3
						Bus aller
						=e.name
					=bar_chart statsbus_path(Configurable[:id_cat_busaller],e.id)
				%div.col.w50
					%h3
						Bus retour
						=e.name
					=bar_chart statsbus_path(Configurable[:id_cat_busretour],e.id)

app/views/admin/index.html.haml
.shadow-1
	%div.top-info.pa1
		%h1 Dashboard admin

	%div.fiche.pa1.brdr-b
		=link_to "Voir tous les graphiques", admin_graph_path, :class => "pure-button pure-button-primary"
		= link_to "Comptes", users_path, :class => "pure-button pure-button-primary"
		= link_to "Paiements", paiements_path, :class => "pure-button pure-button-primary"
		= link_to "Validation paiements", check_paiement_path, :class => "pure-button pure-button-primary"
		= link_to "Remboursements", remboursements_path, :class => "pure-button pure-button-primary"
		%h2 Validation
		= link_to "Validation assurances", add_assurance_personnes_path, :class => "pure-button pure-button-primary"
		= link_to "Validation cautions", add_caution_commandes_path, :class => "pure-button pure-button-primary"
		%h2 Gestion des chambres
		= link_to "Assignement des chambres", assign_chambres_path, :class => "pure-button pure-button-primary"
		%h2 Activitées
		= link_to "Activités", activites_path, :class => "pure-button pure-button-primary"
		%h2 Autre
		= link_to "Check-In", admin_check_in_path, :class => "pure-button pure-button-primary"
		= link_to "Commande boulangerie par chambres", recap_boulangerie_chambres_path, :class => "pure-button pure-button-primary"




	%div.fiche.pa1.brdr-b
		%p
			Nombre de personnes inscrites:
			%span=@nbrPersonnes
		%p
			Nombre de commandes avec au moins un paiement:
			%span=@nombre_commande_avec_paiement
		/ Nombre de personnes non assurées:
		/ %span=@nbrPersonnesNonAssuree


.shadow-1
	%div.top-info.pa1
		%h1 Configuration avancée
	%div.fiche.pa1.brdr-b
		%p Si tu cliques ici, c'est que tu sais ce que tu fais et que t'assume de tout casser.
		%p=link_to "Configuration avancée", admin_configurable_path, :data => { :confirm => "Attention, tu vas toucher à des trucs que même Chuck Norris n'ose pas toucher. T'es bien certain?"}
		%p=link_to "Import des chambres (obsolète pour 2015/16)", import_chambres_path, :data => { :confirm => "Attention, tu vas toucher à des trucs que même Chuck Norris n'ose pas toucher. T'es bien certain?"}
		%p=link_to "Import des lits", import_lits_path, :data => { :confirm => "Attention, tu vas toucher à des trucs que même Chuck Norris n'ose pas toucher. T'es bien certain?"}
		%p=link_to "Import des produits vers les activites", import_activites_path, :data => { :confirm => "Attention, tu vas toucher à des trucs que même Chuck Norris n'ose pas toucher. T'es bien certain?"}