config/routes.rb
LooklaDev::Application.routes.draw do

  resources :gammes

  get "static/index"
  resources :activites do
    member do
      get :export
      post :validate_personne_by_name
    end
    collection do
      get :import
      put :import_product_as_activite , as: :ipap
      put :import_cat_product_as_activite , as: :icpap
      get :validate_personne_by_ean
      post :validate_personne_by_ean
      post :recap
      get :recap
    end
  end

  get "commande_products/check_nombre"
  post "commande_products/check_nombre"
  post "commande_products/validate/:id" => 'commande_products#validate', as: 'commande_products_validate'
  get "admin/index"
  get "admin/check_in"
  get "admin/graph"
  get "home/index"
  get "home/team"
  get "home/pack"
  get "home/pistes"
  get "home/event"
  get "home/histoire"
  get "home/soirees"
  resources :commandes do
	
    member do
      post :add_product
      post :remove_product
      post :maj_cat_product
      get :catalogue
      post :maj_product_personne_preference
    end
    collection do
      post :check_in
      get :export
	  get :export_last_payment
      get :add_caution
      post :validate_caution
      post :validate_caution_batch
      get :index_ean
      post :get_infos
      get :get_infos
    end
    resources :paiements
    get :show_recap
  end
  get 'remboursements' => 'commandes#index_remboursement', as: :remboursements

  get "chart/etatcommande" => "chart#etatcommande"
  get "chart/paiement" => "chart#paiement"
  get "chart/etapepaiement" => "chart#etapepaiement"
  get "chart/tbkcommandes" => "chart#tbkcommandes"
  get "chart/statsinsctiptions" => "chart#statsinsctiptions"
  get "chart/choix_resids" => "chart#choix_resids"
  get "chart/statsbus/:categorie_id/:event_id" => "chart#statsbus", as: :statsbus

  resources :events do
    resources :products
  end
  resources :paiements do
    put :force_validation, :on => :collection
    collection do
      get 'to_moderate'
      get 'export_attente'   
    end
    member do
      get 'remove_from_pending_list'
    end
  end

  post 'paiement-check-lydia-ok' => 'paiements#check_lydia_ok'
  post 'paiement-check-lydia-nok' => 'paiements#check_lydia_nok'
  post 'paiement-check-lydia-expire' => 'paiements#check_lydia_expire'

  get 'paiements-check' => 'paiements#check', as: :check_paiement
  post 'paiements-import-csv' => 'paiements#csv_import', as: :csv_import

  resources :personnes do
    member do
      get 'personne_infos'
      get 'typeresids'
      get 'choix_chambre'
      post 'choix_lit'
      get 'refresh_list_lits'
      post 'personne_infos' => "personnes#update_personne_infos"
      post 'typeresids' => "personnes#update_personne_infos"
      get 'add_commande'
    end
    collection do
      get 'export'
      get 'to_moderate'
      get 'add_assurance'
    end
    resources :commandes do
      resources :events do
        resources :products
      end
    end
  get :autocomplete_personne_nom, :on => :collection
  post :validate_assurance, :on => :collection
  post :validate_assurance_batch, :on => :collection
  end
  resources :products
  get 'productnmbr' => 'comandes#productnmbr'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    member do
      get 'cgu'
      post 'cgu'=>"users#cgu_accept"
      get 'user_infos'
      post 'user_infos'=>"users#update_user_infos"
      get 'dashboard'
      get 'parrainer'
      post 'parrainer'=>"users#create_parrainer"
      get 'new_personne'
    end
    collection do
      get 'to_moderate'
      get 'register/:token', to: "users#register", as: :register
      post 'register/:token'=>"users#create_register"
    end
  end

  resources :chambres, only: [:index, :create] do
    get :autocomplete_personne_nom, :on => :collection
    collection do
      get 'import'
      post 'import' => 'chambres#import_validate'
      get 'assign'
      get 'recap_boulangerie'
    end
    member do
      get 'get_personnes_for'
      get 'add_personne'
      post 'add_personne'
      get 'remove_personne'
      post 'remove_personne'
    end
  end

  resources :preregistrations
  resources :typeresids
  resources :lits do
    collection do
      get 'import'
      post 'import' => 'chambres#import_validate'
    end
  end

  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "landing"
  def index
  	@maintenance=Configurable[:mode_maintenance]

  	resource
  	resource_name
  	devise_mapping

#  	redirect_to dashboard_user_path(current_user) if current_user

 	# flash.now[:notice] = 'Ceci est un message \'notice\'.'
  	# flash.now[:alert] = 'Ceci est un message \'alert\'.'

  end

  def team
  end
  def pack
  end
  def event
  end
  def histoire
  end
  def soirees
  end
  def pistes
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/home_helper.rb
module HomeHelper
def devise_mapping
  @devise_mapping ||= request.env["devise.mapping"]
end
def resource_name
  devise_mapping.name
end

def resource_class
  devise_mapping.to
end
def resource
    @resource ||= User.new
end
end

app/views/home/event.html.haml
.section.sfullscreen
  .container.centrer{:style => "margin-top: 56px;"}
    %h3.header.center{:style => "color: #f99c43;"} SKZ c'est :
    .row
      .col.s12.m4
        .card-panel.light-blue.white-text
          %h4 1400 Gadz'Arts de tous les TBKs
      .col.s12.m4
        .card-panel.light-blue.white-text
          %h4 1 semaine de folie de jour comme de nuit !
      .col.s12.m4
        .card-panel.light-blue.white-text
          %h4 Des souvenirs inoubliables !
    .row.center
      %h4.center.light-blue-text Et cette année nous avons choisi...
      %a.btn-large.waves-effect.waves-light.center{:href => "#lastation"} Découvrir !
#lastation.divider
.section.sfullscreen
  .row{:style => "text-align: center;"}
    %h2.center{:style => "color: #f99c43;"} Saint Sorlin !
    %a{:href => "http://www.saintsorlindarves.com/fr/index-hiver.aspx"}
      %img.center{:src => "/assets/logo-saintsorlin.png"}/
    %br/
    %a{:href => "http://www.saintsorlindarves.com/fr/index-hiver.aspx"} www.saintsorlindarves.com
    %br/
    %br/
    %a.btn-large.waves-effect.waves-light.center{:href => "#lastation_description"} C'est comment ?
#lastation_description.divider{:style => "margin-bottom:0px;"}
.section.sfullscreen.light-blue
  .row{:style => "text-align: center; margin-top:112px;"}
    .col.s12.m8.offset-m2.l6.offset-l3
      .card-panel.white.lighten-5.z-depth-1
        .row.valign-wrapper
          %span.black-text{:style => "text-align:left;"}
            %h6 Saint-Sorlin en bref
            L’hiver, profitez du ski au cœur du grand domaine des Sybelles, d’une ambiance village, d’un ensoleillement et d’un enneigement optimal, ainsi que d’un vaste choix d’activités de loisirs ou de détente.
            %br/
            %br/
            Les Sybelles sont situées entre les vallées de la Maurienne au Nord et de la Romanche au sud,  bordé par les massifs des Aiguilles d’Arves à l’Est  et celui des Grandes Rousses et la chaine de Belledonne à l’ouest.
            %br/
            %br/
            Avec des sommets qui culminent à 3514 m (Aiguille Méridionale),une zone glaciaire importante à St Sorlin, et d’immenses alpages, vierges de toute installation, le pays est un terrain de jeu idéal pour la randonnée été comme hiver.
            Bien enneigés avec des pentes orientées est ou plein nord, beaucoup d’itinéraires gardent une neige froide , excellente pour de fabuleuses descentes. Les dénivelées positives s’échelonnent entre 400 et de 2000 mètres selon les secteurs.
            Autour du glacier de St Sorlin accessible en une heure depuis les remontées mécaniques et le refuge de l’étendard les sommets sont nombreux : Aiguille de laisse, Dôme et cimes  de la Cochette, du  Sauvage et de la Valette et l’Etendard, superbe belvédère de 3464m. 
      %br/
      %a.btn-large.btn-border.waves-effect.waves-light.center{:href => "#lastation_piste"} Et les Pistes ?
      %br/
#lastation_piste.divider
.section.sfullscreen
  .row{:style => "text-align: center;"}
    %a{:href => "/assets/planPistes.jpg"}
      %img{:src => "/assets/planPistes_min.png", :width => "80%"}/
    %br/
    %br/
    %a.btn-large.waves-effect.waves-light.center{:href => "http://live.skiplan.com/moduleweb/2.0/sybelles.php", :target => "_blank"} Voir le plan interactif

app/views/home/histoire.html.haml
.section.sfullscreen
  .centrer{:style => "margin-top: 56px;"}
    %h4.header.center{:style => "color: #03a9f4;"} Ces 25 dernières années, SKZ vous a fait passer des séjours inoubliables...
    .row.center
      %h5.header.col.s12.light{:style => "color: #f99c43;"} ...Et cette année encore, SKZ va vous envoyer du rêve
    .row.center
      %ul#historique
        %li
          %h6 1990 : Les Arcs 1800
        %li
          %h6 1991 : Les Arcs 1800
        %li
          %h6 1992 : Les Arcs 1800
        %li
          %h6 1993 : Val Thorens
        %li
          %h6 1994 : Val Thorens
        %li
          %h6 1995 : Arc 1800
        %li
          %h6 1996 : Val Thorens
        %li
          %h6 1997 : Tignes
        %li
          %h6 1998 : NC
        %li
          %h6 1999 : Les 2 Alpes
        %li
          %h6 2000 : Les Arcs 1800
        %li
          %h6 2001 : Avoriaz
        %li
          %h6 2002 : Les 2 Alpes
        %li
          %h6 2003 : Les Arcs 1800
        %li
          %h6 2004 : Les Ménuires
        %li
          %h6 2005 : La Plagne Bellecôte
        %li
          %h6 2006 : Les 2 Alpes
        %li
          %h6 2007 : Valmorel
        %li
          %h6 2008 : Les Ménuires
        %li
          %h6 2009 : Tignes
        %li
          %h6 2010 : L'Alpe d'Huez
        %li
          %h6 2011 : Les 2 Alpes
        %li
          %h6 2012 : Val Thorens
        %li
          %h6 2013 : Val d’Isère
        %li
          %h6 2014 : Val Thorens
        %li
          %h6 2015 : Tignes
        %li
          %h6 2016 : Risoul
        %li
          %h6 2017 : Les Orres
        %li
          %b
            %h3{:style => "color: #f99c43;"} 2018 : Saint-Sorlin !
          %img.circle{:src => "/assets/logo-saintsorlin.png"}/

app/views/home/index.html.haml
#firstScreen.section.sfullscreen
  .centrer
    %h1.header.center.white-text SKZ
    .row.center
      %h3.header.col.s12.light.white-text Le plus grand évènement de ski étudiant !
    .row.center
      - if user_signed_in?
        - if current_user.inscription_terminee
          = link_to "Mon compte", dashboard_user_path(current_user), class: "btn-large waves-effect"
        - else
          = link_to "S'inscrire", new_user_session_path, class: "btn-large waves-effect pulse"
      - else
        = link_to "S'inscrire", new_user_session_path, class: "btn-large waves-effect pulse"
      %br/
      %br/
      %br/
      %a.btn-large.btn-floating{:href => "#infos_generales"}
        %i.material-icons keyboard_arrow_down
#infos_generales.divider
.section.centrer
  %div
    / Icon Section
    .row
      .col.s12.m4
        .card
          .card-image
            %img{:src => "assets/backgrounds/duski.jpg"}/
            %span.card-title Du ski
          .content
            %p.light Des anim's pistes pour t'éclater ! Que tu sois débutant ou zident tu trouveras forcément ton bonheur !
            = link_to home_pistes_path do
              .card-action
                En savoir plus sur les Anim's Pistes
      .col.s12.m4
        .card
          .card-image
            %img{:src => "assets/backgrounds/soiree2.jpg"}/
            %span.card-title Une expérience 100% gadz !
          .content
            %p.light Une semaine tout compris à prix PG !
            = link_to home_pack_path do
              .card-action
                En savoir plus sur Le Pack
      .col.s12.m4
        .card
          .card-image
            %img{:src => "assets/backgrounds/soiree3.jpg"}/
            %span.card-title Des soirées
          .content
            %p.light Des soirées mémorables jusqu'au bout de la nuit !
            = link_to home_soirees_path do
              .card-action
                En savoir plus sur les Anim's Soirées
    .row.center
      %a.btn-large.btn-floating{:href => "#endScreenDivider"}
        %i.material-icons keyboard_arrow_down
#endScreenDivider.divider
#endScreen.section.sfullscreen
  .centrer
    .row
      .col.s12.teaser
        %iframe{:allowfullscreen => "", :frameborder => "0", :src => "https://www.youtube.com/embed/s98gCyRsKWc?rel=0" }
    .row.center
      %a.btn-large.btn-floating{:href => "#firstScreen"}
        %i.material-icons keyboard_arrow_up

.hiddendiv.common
.drag-target{"data-sidenav" => "nav-mobile", :style => "left: 0px; touch-action: pan-y; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"}

app/views/home/pack.html.haml
.section.sfullscreen
  .container.centrer{:style => "margin-top:70px;"}
    .row
      %ul
        %li
          %h4{:style => "color: #f99c43;"} Le Pack de Base (295€ pour les PGs) contient :
        %li
          %h6 1. Le logement dans la résidence au pied des pistes (Taxes de séjour comprises).
        %li
          %h6 2. Le Pack Food pour 7 jours (matin, midi et soir) quelques soit ton régime alimentaire.
          %p Si tu ne manges pas de porc, nous avons aussi pensé à toi ! Tu pourras le préciser lors de ton inscription.
        %li
          %h6
            3. Le forfait domaine
            %i Les Sybelles
            pour skier pendant tout le séjour sur plus de 310 km de pistes !
          %p Il te sera remis une fois arrivé pour que tu puisse t'éclater toute la semaine !
        %li
          %h6 4. Les animations sur les pistes : compétitions, barbecue... (hors activités spéciales payantes)
          %p
            Plus d'infos ici :
            = link_to "Les Anim's pistes", home_pistes_path
        %li
          %h6 5. Les animations soirées (hors RCC).
          %p
            Plus d'infos ici :
            = link_to "Les Anim's soirées", home_soirees_path
        %li
          %h6 6. Les Goodies !
          %p
            Un casque et plein d'autres surprises...

app/views/home/pistes.html.haml
.section.sfullscreen{:style => "background: url(/assets/backgrounds/montagne5.jpg); background-size: cover; background-attachment: scroll;"}
  .container{:style => "margin-top: 70px;"}
    .row
      .col.s12
        %ul.scollapsible{"data-collapsible" => "accordion"}
          %li.active
            .collapsible-header.active Présentation et contacts
            .collapsible-body
              %span
                %h6 Des anim's sur piste
                %p.light
                  SKZ c'est avant tout de la glisse ! Alors pour rendre l'aventure encore plus folle, la team t'as préparé des anim's sur les pistes.
                  Que tu sois débutant ou pro-rider, tu trouveras forcément ton bonheur !
                %b{:style => "color:red;"} Attention : le port du casque est obligatoire sur toutes les compet', si tu as le tien ne l'oublie pas !
                %br
                %h6 Contacts
                %p Si tu as besoins de plus d'infos n'hésites pas à contacter les anim's pistes par mail : skz-pistes@gadz.org
                %p
                  Pisteusement,
                  %br
                  Diommyliel, Spoutnik, Maréchal, Sorlad'sss
          %li
            .collapsible-header Initiation
            .collapsible-body
              %br
              %span
                Tu n'as jamais tâté la poudreuse ? Tu es impatient de dévaler les pentes ? Les cours d'initiation sont là pour ça !
                %h6 Au programme :
                De la glisse, des chutes et de la glisse ! Tu pourras apprendre aussi bien le ski que le snowboard, si tu ne sais pas quel support choisir avant de prendre tes options de location n'hésite pas à contacter un des Zidents anim'sss pistes pour des conseils avisés.
                Tu pourras ainsi rapidement tracer par tes propres moyens ou encore t'améliorer si tu n'en es pas à tes premiers essais.
                Pour participer, viens aux initiations les dimanche et lundi pour devenir un pro du ski et/ou du snowboard !
                %br
                %b N'oublie pas de t'inscrire pour les cours lors de ton inscription à SKZ, sinon tu ne pourras pas y participer.
                %br
              %i Attention places limitées : seuls les premiers inscrits pourront participer !
          %li
            .collapsible-header Slalom
            .collapsible-body
              %span
                %h6 Le principe :
                Après la reconnaissance du terrain et une qualification chronométrée, tu vas pouvoir t'élancer dans un duel sans pitié sur un parcours tracé spécialement pour vous. L'épreuve se terminera par des finales impressionnantes opposant les meilleurs slalomeurs des TBK ! Et en plus, cette année, le slalom est géant, prépare toi à prendre de la vitesse !
                %br
                %h6 Les catégories
                Ski hommes, Ski femmes, Snowboard hommes, Snowboard femmes
                %br
                Les 3 premiers de chaque catégorie seront récompensés !
                %br
                %b Pendant cette anim's il sera peut être possible de passer ta flèche ! (information à confirmer)
                %br
                %i Attention : seulement 200 places disponibles pour cette animation !
          %li
            .collapsible-header Boarder cross
            .collapsible-body
              %span
                %h6 Principe de la course :
                Départ de front, virages relevés, bosses… tous les coups sont permis… ou presque ! Seuls les premiers seront qualifiés à chaque manche… pour espérer participer à la FINALE tant convoitée ! Va y avoir du sport !
                %br
                1 manche qualificative individuelle chronométrée pour former un tableau final juste,
                %br
                Passage à plusieurs sur un même tracé,
                %br
                Les premiers sont qualifiés pour la manche suivante.
                %br
                Seuls les 3 premiers seront récompensés !
                %br
                Le port d'une dorsale est fortement conseillé pour cette épreuve!
                %br
                %h6 Catégories :
                Ski Hommes, Ski Femmes, Snowboard Hommes, Snowboard Femmes
          %li
            .collapsible-header Derby
            .collapsible-body
              %img.illustration{:src => "/assets/anims/derby2017.jpg"}
              %br
              %span
                Comme une envie de poser le cerveau ? Le derby est alors fait pour toi!
                %h5 Au programme :
                Les règles sont simples, on se met en haut d’une piste, on pose les skis ou les snow en ligne et on recule tous de 10 mètres! Au top, tu cours, tu chausses ta/tes planche(s) et ça part! Le premier arrivé en bas gagne le derby, un prix bien badass, la gloire, la fortune, les fu…. euh enfin voilà quoi ;)
                On te laisse imaginer ce que ça donne à 300...
          %li
            .collapsible-header Barbecue
            .collapsible-body
              %span
                %h6 Une petite faim ?
                La team a prévu d'emmener un barbecue sur les pistes, histoire de te faire un petit casse dalle bien chaud dans le froid de la montagne !
                %br
                Des grosses saucisses pour tous ! C'est un rassemblement de PGs au calme sur les pistes pour se reposer et manger tous ensemble tranquillement ! Un évènement à ne pas rater !
          %li
            .collapsible-header Rallye
            .collapsible-body
              %span
                %h6 Pars à la découverte du domaine de Saint Sorlin d'Arves en participant au Rallye avec tes chticop'sss
                Muni d'un plan des pistes, rends toi en équipe aux quatre coins de la stations pour réaliser de nombreux défis.
                %br
                N de paill'sss et un super moment entre chticop'sss à ne pas rater !
                %br
                Et en plus, pour les meilleures équipes et les plus motivés, de nombreux lots sont à gagner !
          %li
            .collapsible-header Biathlon
            .collapsible-body
              %span
                %h6 Découvre ce sport mythique qui a fait briller la France tant de fois aux JOs d'hiver
                Equipé d'une carabine laser et de raquettes, tu pourras t'initier au biathlon et découvrir que tirer sur une cible après un effort n'est pas si facile que ça !
          %li
            .collapsible-header Handiski
            .collapsible-body
              %span
                %h6 Jamais tu n'auras ressenti de telles sensations !
                Tu as déjà vu des handicapé moteur faire du ski ? Tu t'es toujours demandé comment ils faisaient et ce qu'ils ressentaient ?
                %br
                Viens le découvrir par toi même avec cette anim's que tu n'es pas prêt d'oublier ;)
          %li
            .collapsible-header Descente aux flambeaux
            .collapsible-body
              %span
                %h6 Allumez le feu !
                Rejoins des centaines de PGs pour illuminer la piste lors d'une descente aux flambeaux mémorable.

app/views/home/soirees.html.haml
.section.sfullscreen{:style => "background: url(/assets/backgrounds/soiree4.jpg); background-size: cover; background-attachment: fixed;"}
  .container{:style => "margin-top: 70px;"}
    .row
      .col.s12
        %ul.scollapsible{"data-collapsible" => "accordion"}
          %li
            .collapsible-header
              %i.material-icons> whatshot
              Le Chap' tous les soirs !
            .collapsible-body
              %span
                SKZ, ce n'est pas seulement kiffer la bonne peuf, c'est aussi s'éclater avec des soirées de folie !
                After-ski dès la sortie des pistes et soirée tous les jours !
                %br/
                %br/
                La team anim’sss soirée s’est décuvée N1000 pour vous prévoir du lourd alors pas moy’sss de ne pas en profiter.
                %br/
                La grotte du yéti et son chapit’sss situés au centre du village Gadz vous accueilleront à tout le tap’sss avec des prix imbattables.
                %br/
                %br/
                Il y a des soirées tous les jours avec des thèmes différents, mais un seul objectif commun :
                %h5
                  %b Se mettre bien tous les soirs !!!
          %li
            .collapsible-header Les Afters Skis
            .collapsible-body
              %span
                %h6 Pas l’temps de niaiser, une fois ta journée de ski passée t’as rendev’sss pour l’After-Ski!!!!
                Situé au centre du village Gadz, la Grotte du Yéti te proposera des bières à des prix défiant toute concurrence. Pendant ce temps Synopsis t’engaillera avec de la bonne musique pour bien te détendre (et te préparer à la soirée qui va suivre)°.
                %img.illustration{:src => "/assets/anims/after.jpg"}/
              %li
                .collapsible-header Le RCC
                .collapsible-body
                  %span
                    %h5 Une découverte de la station en mode PG!
                    Après une tournée des bars de la stations (pour les inscrits)° on enchaîne sur une soirée qui réservera bien des surprises et des défis...
    / <img class="img_fullscreen img_top" src="back3.jpg" alt="" >

app/views/home/team.html.haml
.section.sfullscreen
  .container{:style => "margin-top: 56px;"}
    .row
      %h5 La Zidence
      .col.s12.m6.l4.center
        %img.circle{:src => "/assets/lateam/skriniers.jpg"}/
        %span
          %h6 La Zidente
          %h6 Skrinier’ss 174 Li 215
          %h6
            %i Dit Mollier Bathilde
      .col.s12.m6.l4.center
        %img.circle{:src => "/assets/lateam/barbie.jpg"}/
        %span
          %h6 Le Vizi
          %h6 Barbie 98 Ch 215
          %h6
            %i Dit Clement Dubar
      .col.s12.m6.l4.center
        %img.circle{:src => "/assets/lateam/barbie2.jpg"}/
        %span
          %h6 La Tresor'sss
          %h6 Barbie 74 Bo 215
          %h6
            %i Dit Céline Montillet
    .divider{:style => "margin-bottom: 56px;"}
    .row
      %h5 Les Anim's Pistes
      .col.s12.m6.l3.center
        %img.circle{:src => "/assets/lateam/diommyliel.jpg"}/
        %span
          %h6 Diommyliel 162-189 Cl 215
          %h6
            %i Dit Thomas Coudurier
      .col.s12.m6.l3.center
        %img.circle{:src => "/assets/lateam/spoutnik.jpg"}/
        %span
          %h6 Spoutnik 97 Ch 215
          %h6
            %i Dit Guillaume Piedigrossi
      .col.s12.m6.l3.center
        %img.circle{:src => "/assets/lateam/sorladsss.jpg"}/
        %span
          %h6 Sorlad’sss 79 Me 215
          %h6
            %i Dit Theo Marret
      .col.s12.m6.l3.center
        %img.circle{:src => "/assets/lateam/marechal.jpg"}/
        %span
          %h6 Maréchal 93 An 215
          %h6
            %i Dit Rémi Ferrant
    .divider{:style => "margin-bottom: 56px;"}
    .row
      %h5 Les Anim's Soirées
      .col.s12.m6.l3.center
        %img.circle{:src => "/assets/lateam/vinkass.jpg"}/
        %span
          %h6 Vinka’ss 187 Li 215
          %h6
            %i Dit Alexandre Serodon
      .col.s12.m6.l3.center
        %img.circle{:src => "/assets/lateam/pietra.png"}/
        %span
          %h6 Pietra 131-231 Li 215
          %h6
            %i Dit Serena Crocichia
      .col.s12.m6.l3.center
        %img.circle{:src => "/assets/lateam/lemaq.jpg"}/
        %span
          %h6 Le Maq 15 Ch 215
          %h6
            %i Dit Dalil Hassani
      .col.s12.m6.l3.center
        %img.circle{:src => "/assets/lateam/ginfisss.jpg"}/
        %span
          %h6 Gin Fi’ss 58 Li 215
          %h6
            %i Dit Gregoire Perier
    .divider{:style => "margin-bottom: 56px;"}
    .row
      %h5 La Logisitique
      .col.s12.m4.center
        %img.circle{:src => "/assets/lateam/kroche.jpg"}/
        %span
          %h6 Kroché 19 Kin 215
          %h6
            %i Dit Etienne Husson
      .col.s12.m4.center
        %img.circle{:src => "/assets/lateam/krouz.jpg"}/
        %span
          %h6 Krouz 17 Me 215
          %h6
            %i Dit Louis Bouly
      .col.s12.m4.center
        %img.circle{:src => "/assets/lateam/margoulin.jpg"}/
        %span
          %h6 Margoulin 51 Cl 215
          %h6
            %i Dit Léo Rondot
      .col.s12.m6.center
        %img.circle{:src => "/assets/lateam/artsdladal.jpg"}/
        %span
          %h6 Artsd'ladal 58 Cl 215
          %h6
            %i Dit Thibaut Joannard
      .col.s12.m6.center
        %img.circle{:src => "/assets/lateam/ciegeautoss.png"}/
        %span
          %h6 Ciege Auto’ss 143 Li 215
          %h6
            %i Dit Charles Potaux
    .divider{:style => "margin-bottom: 56px;"}
    .row
      %h5 La Com'
      .col.s12.m6.l3.center
        %img.circle{:src => "/assets/lateam/tarplacss.jpg"}/
        %span
          %h6 Tarplac’ss 177 Cl 215
          %h6
            %i Dit Léo Theron
      .col.s12.m6.l3.center
        %img.circle{:src => "/assets/lateam/papheur.jpg"}/
        %span
          %h6 Pap’heur 28 An215
          %h6
            %i Dit Théo Dulou
      .col.s12.m6.l3.center
        %img.circle{:src => "/assets/lateam/hero.jpg"}/
        %span
          %h6 Héro 102 Kin 215
          %h6
            %i Dit Hugo Lefevre
      .col.s12.m6.l3.center
        %img.circle{:src => "/assets/lateam/zoto.jpg"}/
        %span
          %h6 Zoto 98 An 215
          %h6
            %i Dit Nicolas Caligiuri