config/routes.rb
LooklaDev::Application.routes.draw do

  resources :gammes

  get "static/index"
  resources :activites do
    member do
      get :export
      post :validate_personne_by_name
    end
    collection do
      get :import
      put :import_product_as_activite , as: :ipap
      put :import_cat_product_as_activite , as: :icpap
      get :validate_personne_by_ean
      post :validate_personne_by_ean
      post :recap
      get :recap
    end
  end

  get "commande_products/check_nombre"
  post "commande_products/check_nombre"
  post "commande_products/validate/:id" => 'commande_products#validate', as: 'commande_products_validate'
  get "admin/index"
  get "admin/check_in"
  get "admin/graph"
  get "home/index"
  get "home/team"
  get "home/pack"
  get "home/pistes"
  get "home/event"
  get "home/histoire"
  get "home/soirees"
  resources :commandes do
	
    member do
      post :add_product
      post :remove_product
      post :maj_cat_product
      get :catalogue
      post :maj_product_personne_preference
    end
    collection do
      post :check_in
      get :export
	  get :export_last_payment
      get :add_caution
      post :validate_caution
      post :validate_caution_batch
      get :index_ean
      post :get_infos
      get :get_infos
    end
    resources :paiements
    get :show_recap
  end
  get 'remboursements' => 'commandes#index_remboursement', as: :remboursements

  get "chart/etatcommande" => "chart#etatcommande"
  get "chart/paiement" => "chart#paiement"
  get "chart/etapepaiement" => "chart#etapepaiement"
  get "chart/tbkcommandes" => "chart#tbkcommandes"
  get "chart/statsinsctiptions" => "chart#statsinsctiptions"
  get "chart/choix_resids" => "chart#choix_resids"
  get "chart/statsbus/:categorie_id/:event_id" => "chart#statsbus", as: :statsbus

  resources :events do
    resources :products
  end
  resources :paiements do
    put :force_validation, :on => :collection
    collection do
      get 'to_moderate'
      get 'export_attente'   
    end
    member do
      get 'remove_from_pending_list'
    end
  end

  post 'paiement-check-lydia-ok' => 'paiements#check_lydia_ok'
  post 'paiement-check-lydia-nok' => 'paiements#check_lydia_nok'
  post 'paiement-check-lydia-expire' => 'paiements#check_lydia_expire'

  get 'paiements-check' => 'paiements#check', as: :check_paiement
  post 'paiements-import-csv' => 'paiements#csv_import', as: :csv_import

  resources :personnes do
    member do
      get 'personne_infos'
      get 'typeresids'
      get 'choix_chambre'
      post 'choix_lit'
      get 'refresh_list_lits'
      post 'personne_infos' => "personnes#update_personne_infos"
      post 'typeresids' => "personnes#update_personne_infos"
      get 'add_commande'
    end
    collection do
      get 'export'
      get 'to_moderate'
      get 'add_assurance'
    end
    resources :commandes do
      resources :events do
        resources :products
      end
    end
  get :autocomplete_personne_nom, :on => :collection
  post :validate_assurance, :on => :collection
  post :validate_assurance_batch, :on => :collection
  end
  resources :products
  get 'productnmbr' => 'comandes#productnmbr'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    member do
      get 'cgu'
      post 'cgu'=>"users#cgu_accept"
      get 'user_infos'
      post 'user_infos'=>"users#update_user_infos"
      get 'dashboard'
      get 'parrainer'
      post 'parrainer'=>"users#create_parrainer"
      get 'new_personne'
    end
    collection do
      get 'to_moderate'
      get 'register/:token', to: "users#register", as: :register
      post 'register/:token'=>"users#create_register"
    end
  end

  resources :chambres, only: [:index, :create] do
    get :autocomplete_personne_nom, :on => :collection
    collection do
      get 'import'
      post 'import' => 'chambres#import_validate'
      get 'assign'
      get 'recap_boulangerie'
    end
    member do
      get 'get_personnes_for'
      get 'add_personne'
      post 'add_personne'
      get 'remove_personne'
      post 'remove_personne'
    end
  end

  resources :preregistrations
  resources :typeresids
  resources :lits do
    collection do
      get 'import'
      post 'import' => 'chambres#import_validate'
    end
  end

  root :to => "home#index"

end

app/models/activite.rb
class Activite < ActiveRecord::Base
	#################################################
	# Activitée auxquelles le pg/pec's peuvent 
	# s'inscrire
	#################################################

	has_many :personnes, through: :activites_personnes
  has_many :activites_personnes, dependent: :destroy
  belongs_to :event

	#attr_accessible :nom

  def to_s
  	return self.nom
  end

  def to_str
    return self.nom
  end

  def import_from_product(productid)
  	personnes=Product.find(productid).commandes.map{ |c| c.personne}
  	product=Product.find(productid)
  	# récupération des infos
  	self.nom = product.name
  	self.event_id = product.event_id
  	# pour reconnaitre les activité importées depuis un produit
  	self.productid = product.id 

  	#ajout des personnes
  	personnes.each{|p| self.add_personne(p.id)} unless !personnes.any?
  end

  def import_from_cat_product(categorieid,eventid)
    categorie=Categorie.find(categorieid)
    categorie.products.each{ |p|  self.import_from_product(p.id) if p.event_id=eventid}
    self.nom = categorie.nom
    self.event_id = eventid
    self.productid = 1000 + categorieid.to_i
  end

  def add_personne(personneid)
  	self.personnes << Personne.find(personneid)
  end

  def check_personne(personneid)
    activiteid=self.id
    ap=ActivitesPersonne.where(activite_id: activiteid ).find_by! personne_id: personneid
    ap.checked=true
    ap.save
  end

  def is_checked?(personneid)
    activiteid=self.id
    ap=ActivitesPersonne.where(activite_id: activiteid ).find_by! personne_id: personneid
    return ap.checked
  end

  def serialize
    result=Hash.new

    result[:id]=self.id
    result[:nom]=self.nom
    result[:event]=self.event ? self.event.name : "EVENT NON RENSEIGNE"
    result[:open]=self.open ? "LIBRE" : "RESA"
    result[:personnes]=self.activites_personnes.map do |ap|
      personne=Hash.new
      personne[:infos]=ap.personne.infos_completes
      temp_com=ap.personne.commandes.where(event_id:self.event_id).first
      personne[:commande]=temp_com.idlong if temp_com
      temp_chambre=ap.personne.chambres.where(event_id:self.event_id).first
      personne[:chambre]=temp_chambre.identifiant if temp_chambre
      personne[:checked]=ap.checked ? "Oui" : "Non"
      personne
    end
    result

  end

end

app/controllers/activites_controller.rb
# -*- encoding : utf-8 -*-
class ActivitesController < ApplicationController

  before_action :admin_only

  def index
  	@activite=Activite.all
    @events=Event.all
  end

  def new
    @activite = Activite.new
    @events=Event.all
  end

  def create
    @activite = Activite.new(activite_params)
    authorize! :create, @activite

    respond_to do |format|
      if @activite.save
        format.html { redirect_to activites_path, notice: 'Votre activite a bien été créée' }
        format.json { head :no_content }
      else
        format.html { render 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    set_activite
    authorize! :update, @activite
    @events=Event.all.to_a
    @packs=Pack.all
  end

  def update
    set_activite
    authorize! :create, @activite

    respond_to do |format|
      if @activite.update(activite_params)
        format.html { redirect_to activites_path, notice: 'Votre activite a bien été éditée' }
        format.json { head :no_content }
      else
        format.html { render 'edit' }
        format.json { render json: @activite.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  	@activite=Activite.find(params[:id])
  	@personnes=@activite.personnes
    @nbtotal=@personnes.count
    @nbcheck=ActivitesPersonne.where(activite_id: params[:id], checked: true).count
    @parchambre=true if @activite.productid.to_i >= 1000
  end

  def recap
    @chambre=Chambre.find(params[:chambreid])
    @activite=Activite.find(params[:activityid])
    @categorie_id=params[:categorieid].to_i

  end

  def import
  	@products=Product.all
  	@categories = Categorie.all
    @events=Event.all
  end

  def import_product_as_activite
  	activite= Activite.new
  	activite.import_from_product(params[:productid])
    activite.open=false
    activite.save!
    redirect_to :back, notice: "Activitée ajoutée"
  end

  def import_cat_product_as_activite
    activite= Activite.new
    activite.import_from_cat_product(params[:categorieid],params[:eventid])
    activite.open=false
    activite.save!
    redirect_to :back, notice: "Activitée ajoutée"
  end

  def validate_personne_by_name
   activityid=params[:id]
   activite=Activite.find(activityid)
   eventid=activite.event_id
   personneid=params[:id_pers]
   commande=Personne.find(personneid).commandes.find_by event_id: eventid
   ean=commande.ean
   redirect_to validate_personne_by_ean_activites_path(:id => activityid, :ean => ean), method: :post 

 end

 def validate_personne_by_ean
    # 2 comportement différents en fonction de si c'est une catégorie importée où non.
    # on verifie ça sur l'id produit. Si plus grand que 1000 c'est une categorie. c'est sale. je sais.
    ean=params[:ean]
    activityid=params[:id].to_i
    commandes=Commande.where(ean: ean )

    if !commandes.any?
      # si on ne trouve pas de commande avec cet EAN
      redirect_to activite_path(activityid), alert: "Cette commande / personne n'existe pas"
    else

      personne=commandes.take!.personne

      personneid=personne.id
      activite=Activite.find(activityid)
      
      # on verifie que c'est une activite qui vient d'un produit ou categorie de produits
      if activite.productid.to_i >= 1000
        chambre=personne.chambres.take!
        personnes=chambre.personnes
        #l'activité est forcement not open
        # on verifie si qq'un de la chanbre est déj) passé

        if personnes.map{|p| ActivitesPersonne.where(activite_id:activityid, personne_id:p.id).take!.checked unless ActivitesPersonne.where(activite_id:activityid, personne_id:p.id).empty?}.include? true
          redirect_to activite_path(activityid), alert: personnes.map { |p| p.nom_complet + " " }.to_s + " sont déjà passés"

       else

        personnes.each{|p| activite.check_personne(p.id) unless (activite.personnes.find_by id: p.id).nil?}
        # on recalcule l'id de la categorie
        categorieid=activite.productid.to_i - 1000
        redirect_to recap_activites_path(:activityid => activityid, :chambreid => chambre.id, :categorieid => categorieid), notice: "Passage de "+ personnes.map { |p| p.nom_complet + " " }.to_s + " Validé!"
      end
      else


      # si l'activité est open, on ajoute la personne à la liste. Sinon on la refuse.
      if activite.open
        #ah bah oui il faut le coder ça
        if activite.personnes.find_by(id: personneid).present?
          redirect_to activite_path(activityid), alert:  personne.nom_complet + " est déjà passé!"
        else
          activite.add_personne(personneid)
          activite.check_personne(personneid)
          redirect_to activite_path(activityid), notice: "Passage de "+ personne.nom_complet + " Validé!"

        end
      else
        if activite.personnes.find_by(id: personneid).present?
          #si la personne existe bien dans la liste on vérifie que si elle est déjà passée
          if activite.is_checked?(personneid)
            redirect_to activite_path(activityid), alert:  personne.nom_complet + " est déjà passé!"

          else
            activite.check_personne(personneid)
            redirect_to activite_path(activityid), notice: "Passage de "+ personne.nom_complet + " Validé!"
          end
        else
          redirect_to activite_path(activityid), alert:  personne.nom_complet + " N'est pas inscrit(e)!"
        end
      end
    end
  end
end

def export
  set_activite

  @activite = @activite.serialize

  respond_to do |format|
    format.xls do
      response.headers['Content-Disposition'] = 'attachment; filename="' +"export_activite_"+Date.today.to_s+ '.xls"'
    end
  end

end

private

def activite_params
  params.require(:activite).permit(:nom,:event_id,:open)
end

def set_activite
  @activite = Activite.find(params[:id])
end

end

app/helpers/activite_helper.rb
module ActiviteHelper
end

app/views/activites/_form.html.haml
= form_for @activite do |f|
  - if @activite.errors.any?
    #error_explanation
      %h2= "#{pluralize(@activite.errors.count, "error")} prohibited this activite from being saved:"
      %ul
        - @activite.errors.full_messages.each do |msg|
          %li= msg
  .field.pure-control-group
    =f.label :nom 
    =f.text_field :nom
  .field.pure-control-group
    =f.label :event_id, "Evenement"
    =f.select :event_id, @events.map{|t| [t.name,t.id]}, :class => "pure-input-1-3"
  .field.pure-control-group
    =f.label :open, "Inscription libre"
    =f.check_box :open

  .actions
    =f.submit "Enregistrer"

app/views/activites/edit.html.haml
%div.top-info.pa1
  %h1 Edition d'Activité
%div.fiche.pa1.brdr-b
  = render 'form'
  = link_to 'Retour', activites_path

app/views/activites/export.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String"><%= @activite[:id] %></Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">Nom</Data></Cell>
        <Cell><Data ss:Type="String"><%= @activite[:nom] %></Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">Event</Data></Cell>
        <Cell><Data ss:Type="String"><%= @activite[:event] %></Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">Open</Data></Cell>
        <Cell><Data ss:Type="String"><%= @activite[:open] %></Data></Cell>
      </Row>
      <Row>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">Personnes</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">Infos</Data></Cell>
        <Cell><Data ss:Type="String">Commande ID</Data></Cell>
        <Cell><Data ss:Type="String">Chambre ID</Data></Cell>
        <Cell><Data ss:Type="String">Checked</Data></Cell>
      </Row>

    <% @activite[:personnes].each do |p| %>
      <Row>
        <Cell><Data ss:Type="String"><%= p[:infos] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= p[:commande] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= p[:chambre] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= p[:checked] %></Data></Cell>

      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/activites/import.html.haml
%div.top-info.pa1
  %h1 Import d'une activité


- @categories.each_with_index do |ca, i|
  -unless ca.nom.blank?
    %div.pa1.fiche.brdr-b
      %h2=ca.nom
      %div
        - @events.each do |e|
          =link_to "Importer catégorie event " + e.id.to_s, {:controller => :activites, :action => :import_cat_product_as_activite, :categorieid => ca.id , :eventid => e.id}, {:method => :put, :class => "pure-button pure-button-error"}
      %table.striped.alternate
        %thead
          %tr
            %th Ajouter
            %th Produit
            %th Quantitée totale
            %th Prix (€)
            %th Date limite de réservation
            -if not @evenement
              %th Evenement
          %tbody
            - @products.each do |prd|
              -if prd.categorie_id==i+1
                %tr
                  %td=link_to "Ajouter", {:controller => :activites, :action => :import_product_as_activite, :productid => prd.id}, {:method => :put, :class => "pure-button pure-button-error"}
                  %td=link_to prd.name, product_path(prd.id)
                  %td=prd.stock
                  %td=prd.price_euro
                  %td=prd.echeance
                  -if not @evenement
                    %td=prd.event.name

app/views/activites/index.html.haml
%div.top-info.pa1
	%h1 Activitées

	=link_to "Créer une activité", new_activite_path, :class => "pure-button pure-button-success"
- @events.each do |e|
	%div.pa1.fiche.brdr-b
		%h2=e.name
		%table.striped.alternate
			%thead
				%tr
					%th Nom
					%th Inscrits
					%th Inscription libre
					%th Importée

			%tbody
				- @activite.each do |a| 
					-if a.event_id==e.id
						%tr
							%td=link_to a.nom,activite_path(a.id)
							%td=a.personnes.count
							%td=a.open
							%td=a.productid
							%td=link_to "Edit", edit_activite_path(a.id), :class => "pure-button pure-button-primary pure-button-xsmall "

app/views/activites/new.html.haml
%div.top-info.pa1
  %h1 Création d'Activité
%div.fiche.pa1.brdr-b
  = render 'form'
  = link_to 'Retour', activites_path

app/views/activites/recap.html.haml
%div.top-info.pa1
  %h1
    Activite: #{@activite.nom}
  %h2

%div.pa1.fiche.brdr-b
  %h2 Recherche par code barre
  =form_tag validate_personne_by_ean_activites_path :method => :post do
    =text_field_tag 'ean', '' , :size => 13 ,:autofocus => true
    =hidden_field_tag "id", params[:activityid]
    = submit_tag 'Check!', :class => "pure-button pure-button-success pure-button-xsmall "


%div.fiche.pa1.brdr-b
  %h2= "Chambres n° #{@chambre.identifiant} "
  -@chambre.personnes.each do |p|
    %h3= p.nom_complet
    %table
      -p.commandes.find_by_event_id(@chambre.event_id).products.where(categorie_id: @categorie_id).each do |pr|
        %tr
          %td=pr.name
          %td=p.commandes.find_by_event_id(@chambre.event_id).commande_products.find_by_product_id(pr.id).nombre

app/views/activites/show.html.haml
%div.top-info.pa1
  %h1
    Activite: #{@activite.nom}
  %h2
    Passés:
    =@nbcheck.to_s
    Total:
    =@nbtotal

%div.pa1.fiche.brdr-b
  %p Inscription libre: #{@activite.open}
  %p Inscription par chambre: #{@parchambre}
    

/ %div.pa1.fiche.brdr-b
/   %h2 Rechercher une personne NE PAS UTILISER
/   %span La recherche se fait par le nom de famille
/   %div
/     =form_tag validate_personne_by_name_activite_path(@activite.id), :method => :post do
/       =autocomplete_field_tag 'nom', '', autocomplete_personne_nom_personnes_path, :id_element=>"#id_pers", :size => 75
/       =hidden_field_tag "id_pers"
/       = submit_tag 'Check!', :class => "pure-button pure-button-success pure-button-xsmall "

%div.pa1.fiche.brdr-b
  %h2 Recherche par code barre
  =form_tag validate_personne_by_ean_activites_path :method => :post do
    =text_field_tag 'ean', '' , :size => 13 ,:autofocus => true
    =hidden_field_tag "id", params[:id]
    = submit_tag 'Check!', :class => "pure-button pure-button-success pure-button-xsmall "



/ :autofocus => true
=link_to "Export Excel", export_activite_path(id: @activite.id,format: 'xls')
%div.pa1.fiche.brdr-b
  %table.striped.alternate
    %thead
      %tr
        %th Nom
        %th Inscrits

    %tbody
      - @personnes.each do |a|
        %tr
          %td=a.nom_complet
          %td