config/routes.rb
LooklaDev::Application.routes.draw do

  resources :gammes

  get "static/index"
  resources :activites do
    member do
      get :export
      post :validate_personne_by_name
    end
    collection do
      get :import
      put :import_product_as_activite , as: :ipap
      put :import_cat_product_as_activite , as: :icpap
      get :validate_personne_by_ean
      post :validate_personne_by_ean
      post :recap
      get :recap
    end
  end

  get "commande_products/check_nombre"
  post "commande_products/check_nombre"
  post "commande_products/validate/:id" => 'commande_products#validate', as: 'commande_products_validate'
  get "admin/index"
  get "admin/check_in"
  get "admin/graph"
  get "home/index"
  get "home/team"
  get "home/pack"
  get "home/pistes"
  get "home/event"
  get "home/histoire"
  get "home/soirees"
  resources :commandes do
	
    member do
      post :add_product
      post :remove_product
      post :maj_cat_product
      get :catalogue
      post :maj_product_personne_preference
    end
    collection do
      post :check_in
      get :export
	  get :export_last_payment
      get :add_caution
      post :validate_caution
      post :validate_caution_batch
      get :index_ean
      post :get_infos
      get :get_infos
    end
    resources :paiements
    get :show_recap
  end
  get 'remboursements' => 'commandes#index_remboursement', as: :remboursements

  get "chart/etatcommande" => "chart#etatcommande"
  get "chart/paiement" => "chart#paiement"
  get "chart/etapepaiement" => "chart#etapepaiement"
  get "chart/tbkcommandes" => "chart#tbkcommandes"
  get "chart/statsinsctiptions" => "chart#statsinsctiptions"
  get "chart/choix_resids" => "chart#choix_resids"
  get "chart/statsbus/:categorie_id/:event_id" => "chart#statsbus", as: :statsbus

  resources :events do
    resources :products
  end
  resources :paiements do
    put :force_validation, :on => :collection
    collection do
      get 'to_moderate'
      get 'export_attente'   
    end
    member do
      get 'remove_from_pending_list'
    end
  end

  post 'paiement-check-lydia-ok' => 'paiements#check_lydia_ok'
  post 'paiement-check-lydia-nok' => 'paiements#check_lydia_nok'
  post 'paiement-check-lydia-expire' => 'paiements#check_lydia_expire'

  get 'paiements-check' => 'paiements#check', as: :check_paiement
  post 'paiements-import-csv' => 'paiements#csv_import', as: :csv_import

  resources :personnes do
    member do
      get 'personne_infos'
      get 'typeresids'
      get 'choix_chambre'
      post 'choix_lit'
      get 'refresh_list_lits'
      post 'personne_infos' => "personnes#update_personne_infos"
      post 'typeresids' => "personnes#update_personne_infos"
      get 'add_commande'
    end
    collection do
      get 'export'
      get 'to_moderate'
      get 'add_assurance'
    end
    resources :commandes do
      resources :events do
        resources :products
      end
    end
  get :autocomplete_personne_nom, :on => :collection
  post :validate_assurance, :on => :collection
  post :validate_assurance_batch, :on => :collection
  end
  resources :products
  get 'productnmbr' => 'comandes#productnmbr'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    member do
      get 'cgu'
      post 'cgu'=>"users#cgu_accept"
      get 'user_infos'
      post 'user_infos'=>"users#update_user_infos"
      get 'dashboard'
      get 'parrainer'
      post 'parrainer'=>"users#create_parrainer"
      get 'new_personne'
    end
    collection do
      get 'to_moderate'
      get 'register/:token', to: "users#register", as: :register
      post 'register/:token'=>"users#create_register"
    end
  end

  resources :chambres, only: [:index, :create] do
    get :autocomplete_personne_nom, :on => :collection
    collection do
      get 'import'
      post 'import' => 'chambres#import_validate'
      get 'assign'
      get 'recap_boulangerie'
    end
    member do
      get 'get_personnes_for'
      get 'add_personne'
      post 'add_personne'
      get 'remove_personne'
      post 'remove_personne'
    end
  end

  resources :preregistrations
  resources :typeresids
  resources :lits do
    collection do
      get 'import'
      post 'import' => 'chambres#import_validate'
    end
  end

  root :to => "home#index"

end

app/models/product.rb
class Product < ActiveRecord::Base

	#################################################
	# Les produits commandable
	#################################################
	has_many :commandes, through: :commande_products
	has_many :commande_products, dependent: :destroy
        has_many :product_personne_preferences

	has_many :pack
	belongs_to :categorie
	belongs_to :event
        belongs_to :gamme
        belongs_to :type_product
        belongs_to :option_sup

	#attr_accessible :name, :price, :stock, :echeance
        attr_accessor :couleur_cadre, :couleur_verre

	def to_s
		return self.name
	end

	def to_str
		return self.name
	end

	def price_euro
		return self.price / 100.0
	end

	def restant
		return nil if self.stock == 0
		self.stock ||=0
		self.stock.to_i - self.commande_products.map{|cp| cp.nombre}.sum
	end

	def reste? (nbr = 0)

		return true if self.stock == 0 || self.stock.blank?

		self.restant > 0

	end

        def restant_masque
          if self.option_sup_id != nil
            c_cadre = self.option_sup.couleur_cadre           
            cumul = 0
            OptionSup.where(couleur_cadre: c_cadre).each do |o|
              if o.products.first.commande_products.present?
                commandes= o.products.first.commande_products.map{|cp| cp.nombre}.sum
                cumul += commandes
              end
            end
            if self.stock.nil? or self.stock == 0
              return "infini"
            else
              return self.stock.to_i - cumul
            end
          end
        end

        def reste_masque?
   	  return true if self.stock == 0 || self.stock.nil?
          self.restant_masque > 0
        end

        def product_id
          return self.id
        end
        def anims_id
          return self.id
        end

        def oui
          return "Oui"
        end

        def name_gamme
          return self.gamme.nom + " - " + self.name
        end

        def self.preferences_form
          arr = []
          self.preferences.each do |p|
            if p == "1"
              arr << [p.to_s+" (1er choix)",p.to_i]
            elsif p == "2"
              arr << [p.to_s+" (2nd choix)",p.to_i]
            else
              arr << [p.to_s+" (3ème choix)",p.to_i]
            end
          end
          return arr
	end

        def self.preferences
          count = 3
          array = []
          (1..count).each do |i|
            array << i.to_s
          end
          return array
        end

end

app/controllers/products_controller.rb
# -*- encoding : utf-8 -*-
class ProductsController < ApplicationController

  before_action :check_register_workflow

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:event_id]
      @products = Product.all.where(event_id: params[:event_id]).order(:id)
      @evenement = Event.find(params[:event_id]).name
    else
      @products = Product.all.order(:id)
    end
    authorize! :read, @products
    @categories = Categorie.all.order(:id)
    @titre = "Produit"

  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @evenement = @product.event.name
  end

  # GET /products/new
  def new
    authorize! :read_admin, User
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    authorize! :read_admin, User
  end

  # POST /products
  # POST /products.json
  def create
    authorize! :read_admin, User
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    authorize! :read_admin, User
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    authorize! :read_admin, User
    # @product.destroy
    # respond_to do |format|
    #   format.html { redirect_to products_url }
    #   format.json { head :no_content }
    # end
  end

  # def product_add_to_commande
  #   commande=Personne
  #   Product.each do |prd|
  #     if params["prd_" + pdr.id.to_s]
  # end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name,:stock,:max_par_personne,:event_id,:categorie_id,:price,:gamme_id,:en_attente,:option_sup_id,:image,:type_product_id,:votable)
    end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .container 
    .field.pure-control-group
      = f.label :name
      <br/>
      = f.text_field :name, :class => "pure-input-1-3"
    .field.pure-control-group
      = f.label :event_id
      <br/>
      = f.select :event_id, Event.all.map{|g| [g.name,g.id]}, :class => "pure-input-1-3"
    .field.pure-control-group
      = f.label :categorie_id
      <br/>
      = f.select :categorie_id, Categorie.all.map{|g| [g.nom,g.id]}, :class => "pure-input-1-3"
    .field.pure-control-group
      = f.label :price
      <br/>
      = f.text_field :price, :class => "pure-input-1-3"
    .field.pure-control-group
      = f.label :stock
      <br/>
      = f.text_field :stock, :class => "pure-input-1-3"
    .field.pure-control-group
      = f.label :max_par_personne
      <br/>
      = f.text_field :max_par_personne, :class => "pure-input-1-3"
    .field.pure-control-group
      = f.label :echeance
      <br/>
      = f.date_field :echeance, :class => "pure-input-1-3"
    .field.pure-control-group
      = f.label :description
      <br/>
      = f.text_field :description, :class => "pure-input-1-3"
    .field.pure-control-group
      = f.label "Gamme de ski (ne sert que pour les produits de ski)"
      <br/>
      = f.select :gamme_id, options_for_select(Gamme.all.map{|t| [t.nom,t.id]}), include_blank: true
    .field.pure-control-group
      = f.label "Type de produit (sert pour le moment à distinguer certaines anims: slalom,derby, etc )"
      <br/>
      = f.select :type_product_id, options_for_select(TypeProduct.all.map{|t| [t.nom,t.id]}), include_blank: true
      <br/>
    .field.pure-control-group
      = f.check_box :votable
      = f.label :votable, "Preference ? (Sert pour les anim's qu'on peut noter)"
    <br/>
    .field.pure-control-group
      = f.label "Option supplémentaire (sert pour d'éventuelles options supplémentaires (cette année les masques Ryft))"
      <br/>
      = f.select :option_sup_id, options_for_select(OptionSup.all.map{|t| ["#{t.nom} #{t.couleur_cadre}/#{t.couleur_verre} ",t.id]}), include_blank: true


      = f.submit 'Enregistrer', class: "pure-button pure-button-success"

app/views/products/edit.html.haml
%div.top-info.pa1
	%h1 Edition de Produit
%div.fiche.pa1.brdr-b

	= render 'form'

	= link_to 'Show', @product
	\|
	= link_to 'Back', products_path

app/views/products/index.html.haml
%div.top-info.pa1
  %h1
    Produits 
    =@evenement

    =link_to " Créer un produit", new_product_path, :class => "pure-button pure-button-success  md-add-circle-outline right"
/ # =form_tag( product_commande_path, :method => :post) do
- @categories.each_with_index do |ca, i|
  -unless ca.nom.blank?
    %div.pa1.fiche.brdr-b
      %h2=ca.nom
      %table.striped.alternate
        %thead
          %tr
            %th Produit
            %th Quantité totale
            %th Quantité commandée [toutes commandes confondues]
            %th Quantité commandée [commandes payées]
            %th Prix (€)
            %th Date limite de réservation
            -if not @evenement
              %th Evenement
          %tbody
            - @products.each do |prd|
              -if prd.categorie_id==i+1
                %tr
                  %td=link_to prd.name, product_path(prd.id)
                  %td=prd.stock
                  %td=prd.commande_products.map{|cp| cp.nombre}.sum
                  %td=prd.commandes.select{|c| c.montant_paye > 0}.count
                  %td=prd.price_euro
                  %td=prd.echeance
                  -if not @evenement
                    %td=prd.event.name
                  
/ #  =submit_tag 'Valider'

app/views/products/new.html.haml
%div.top-info.pa1
  %h1 Création de Produit
%div.fiche.pa1.brdr-b

  = render 'form'

  = link_to 'Back', products_path

app/views/products/show.html.haml
%div.top-info.pa1
	%h1=@product.name
%div.fiche.pa1.brdr-b
	%p
		Evenement:
		=@evenement
	%p
		Categorie:
		=@product.categorie.nom
	%p
		Stock: 
		=@product.stock
	%p
		Prix:
		=@product.price_euro
	%p
		Date limite de résevation:
		=@product.echeance
	%p
		Description:
		=@product.description
	%p
		Max par personne:
		=@product.max_par_personne
	-if can? :see_admin, User
		%p
			=link_to 'Editer', edit_product_path(@product), :class => "pure-button pure-button-primary"
			/ =link_to 'Supprimer', @procut, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "pure-button pure-button-error"